fastcoll:
	g++ -O3 *.cpp -lboost_filesystem -lboost_program_options -lboost_system -o fastcoll
fastcoll-static:
	g++ -O3 *.cpp -l:libboost_filesystem.a -l:libboost_program_options.a -l:libboost_system.a -o fastcoll

